import org.code.neighborhood.*;
public class PixelPainter extends repeats {
  public void paintSymbol(){
    paintOutside();
    paintInside();
  }
  /*
  *Paints the outside of the drawing
  */
  public void paintOutside() {
    move3();
    paint6("White");
    paint("Gainsboro");
    move();
    turnRight();
    move();
    turnLeft();
    paint("Gainsboro");
    move();
    turnRight();
    move();
    turnLeft();
    paint("Gainsboro");
    move();
    turnRight();
    move();
    turnLeft();
    paint("White");
    turnRight();
    paint("White");
    move();
    paint5("Gainsboro");
    turnRight();
    move();
    turnLeft();
    move();
    paint("Gainsboro");
    turnRight();
    move();
    turnLeft();
    move();
    paint("Gainsboro");
    move();
    turnRight();
    move();
    paint6("Gainsboro");
    move();
    turnRight();
    move();
    paint("Gainsboro");
    move();
    turnLeft();
    move();
    paint("Gainsboro");
    move();
    turnRight();
    move();
    paint6("White");
    move();
    turnRight();
    move();
    turnLeft();
    paint("White");
    move();
    turnRight();
    move();
    turnLeft();
    paint("White");
  }
  /*
  * Paints the outside of the drawing
  */
  public void paintInside() {
    turnRight();
    move3();
    turnRight();
    paint4("LightGray");
    move();
    paint("Gray");
    turnRight();
    move();
    paint("Gray");
    turnLeft();
    move();
    paint("Gray");
    turnLeft();
    move();
    paint("White");
    turnLeft();
    turnLeft();
    move2();
    paint("Gray");
    turnLeft();
    move();
    turnRight();
    paint2("Gray");
    turnLeft();
    move();
    turnRight();
    paint2("Gray");
    turnLeft();
    move();
    turnLeft();
    move();
    paint("Gray");
    move7();
    paint("DimGray");
    move();
    turnLeft();
    move();
    paint("Gainsboro");
    turnLeft();
    move();
    paint("Gainsboro");
    turnRight();
    move();
    paint("Gainsboro");
    turnLeft();
    move();
    paint("Gainsboro");
    turnRight();
    move();
    turnLeft();
    paint3("Gainsboro");
    turnRight();
    move();
    paint5("Gainsboro");
   
  }
}